### ISSUE TITLE
YAML lists indented with tabs

### ISSUE THREAD

**Issue by lnxgrl** [CaliStyle/markdown-it-meta#2]
The plugin does not parse yaml lists correctly when they are indented with tabs

```
---
title: A post about cats
description: Cats are very awesome, and here is why.
tags:
	- cats
	- mew
---
```

crashes when the list is indented with tabs

However,

```
---
title: A post about cats
description: Cats are very awesome, and here is why.
tags:
    - cats
    - mew
---
```

is indented with spaces and works as expected.

Thanks !

**Comment by lil5** [comment]
I advise you read this comment related to the method used to parsing YAML in this project

https://github.com/nodeca/js-yaml/issues/80#issuecomment-158592334

**Comment by lil5** [comment]
@ninivert  @scott-wyatt  As it is not supported please close this issue
